name: Docker image builder
on:
  push:
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    -
      name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: ghcr.io/${{ github.repository }} # list of Docker images to use as base name for tags
        tag-sha: true # add git short SHA as Docker tag
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to ghcr.io
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    -
      name: Login to docker.pkg.github.com
      uses: docker/login-action@v1 
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ github.token }}
    -
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        build-args: |
          "SSH_KEY=${{ secrets.SSH_KEY }}"
    -
      name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}  
